language: php
php:
  - 7
  - 7.1
  - 7.2
  - nightly
env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""
install:
  - composer self-update
before_script:
  - composer update --prefer-source $PREFER_LOWEST
script:
  - phpunit
after_success:
  - ./bin/phpcs --standard=psr2 src
  - ./bin/phpmd src text cleancode,codesize,controversial,design,unusedcode
  - ./bin/phpcpd src
  - ./bin/pdepend --summary-xml=/tmp/summary.xml --jdepend-chart=/tmp/jdepend.svg --overview-pyramid=/tmp/pyramid.svg src
  - ./bin/phploc src