services:
    __defaults:
        public: false
        autowire: true
        autoconfigure: true

    Printdeal\PandosearchBundle\Locator\HttpClientLocator: ~

    Printdeal\PandosearchBundle\Builder\SearchCriteriaBuilder: ~
    Printdeal\PandosearchBundle\Builder\SuggestCriteriaBuilder: ~
    Printdeal\PandosearchBundle\Service\QueryBuilder: ~

    Printdeal\PandosearchBundle\Service\SearchService:
        arguments:
            - '@printdeal_pandosearch.locator.http_client_locator'
            - '@printdeal_pandosearch.builder.search_criteria_builder'
            - '@printdeal_pandosearch.builder.suggest_criteria_builder'
            - '@jms_serializer.serializer'

    printdeal_pandosearch:
        alias: '@Printdeal\PandosearchBundle\Service\SearchService'
        public: true

    Printdeal\PandosearchBundle\DeserializationHandler\SearchDeserializationHandler:
        abstract: true
        tags:
            - { name: 'jms_serializer.subscribing_handler' }

    Printdeal\PandosearchBundle\DeserializationHandler\SuggestionDeserializationHandler:
        abstract: true
        tags:
            - { name: 'jms_serializer.subscribing_handler' }

