services:
    printdeal_pandosearch.locator.http_client_locator:
        class: Printdeal\PandosearchBundle\Locator\HttpClientLocator
        public: false
        arguments:
            - []

    printdeal_pandosearch.builder.search_criteria_builder:
        class: Printdeal\PandosearchBundle\Builder\SearchCriteriaBuilder
        public: false
        arguments:
            - '@jms_serializer'
            - []
        tags: ['printdeal.pandosearch.builder']

    printdeal_pandosearch.builder.suggest_criteria_builder:
        class: Printdeal\PandosearchBundle\Builder\SuggestCriteriaBuilder
        public: false
        arguments:
            - '@jms_serializer.serializer'
            - []
        tags: ['printdeal.pandosearch.builder']

    printdeal_pandosearch.service.search_service:
        class: Printdeal\PandosearchBundle\Service\SearchService
        public: false
        arguments:
            - '@printdeal_pandosearch.locator.http_client_locator'
            - '@printdeal_pandosearch.builder.search_criteria_builder'
            - '@printdeal_pandosearch.builder.suggest_criteria_builder'
            - '@jms_serializer.serializer'

    printdeal_pandosearch: '@printdeal_pandosearch.service.search_service'

    printdeal_pandosearch.deserialization_handler.search_response:
        class: Printdeal\PandosearchBundle\DeserializationHandler\SearchResponseDeserializationHandler
        arguments:
            - '%printdeal_pandosearch.deserialization_parameters.search_response_entity%'
            - '@jms_serializer.serializer'
        tags:
            - { name: 'jms_serializer.subscribing_handler' }

    printdeal_pandosearch.deserialization_handler.suggestion_response:
        class: Printdeal\PandosearchBundle\DeserializationHandler\SuggestionResponseDeserializationHandler
        arguments:
            - '%printdeal_pandosearch.deserialization_parameters.suggestion_response_entity%'
            - '@jms_serializer.serializer'
        tags:
            - { name: 'jms_serializer.subscribing_handler' }