services:
    printdeal_pandosearch.locator.guzzle_client_locator:
        class: Printdeal\PandosearchBundle\Locator\GuzzleClientLocator
        public: false

    printdeal_pandosearch.builder.search_criteria_builder:
        class: Printdeal\PandosearchBundle\Builder\SearchCriteriaBuilder
        public: false
        arguments:
            - '@jms_serializer'
            - []
        tags: ['printdeal.pandosearch.builder']

    printdeal_pandosearch.builder.suggest_criteria_builder:
        class: Printdeal\PandosearchBundle\Builder\SuggestCriteriaBuilder
        public: false
        arguments:
            - '@jms_serializer.serializer'
            - []
        tags: ['printdeal.pandosearch.builder']

    printdeal_pandosearch.service.search_service:
        class: Printdeal\PandosearchBundle\Service\SearchService
        public: false
        arguments:
            - '@printdeal_pandosearch.locator.guzzle_client_locator'
            - '@printdeal_pandosearch.builder.search_criteria_builder'
            - '@printdeal_pandosearch.builder.suggest_criteria_builder'
            - '@jms_serializer.serializer'

    printdeal_pandosearch: '@printdeal_pandosearch.service.search_service'