services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Printdeal\PandosearchBundle\Locator\HttpClientLocator: ~

    Printdeal\PandosearchBundle\Builder\SearchCriteriaBuilder: ~
    Printdeal\PandosearchBundle\Builder\SuggestCriteriaBuilder: ~
    Printdeal\PandosearchBundle\Service\QueryBuilder: ~

    Printdeal\PandosearchBundle\Service\SearchService: ~

    printdeal_pandosearch:
        alias: 'Printdeal\PandosearchBundle\Service\SearchService'
        public: true

    Printdeal\PandosearchBundle\DeserializationHandler\SearchDeserializationHandler:
        autowire: false
        abstract: true
        tags:
            - { name: 'jms_serializer.subscribing_handler' }

    Printdeal\PandosearchBundle\DeserializationHandler\SuggestionDeserializationHandler:
        autowire: false
        abstract: true
        tags:
            - { name: 'jms_serializer.subscribing_handler' }

